var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...nextauth]/route.js")
R.c("server/chunks/5bcb1_next_d5ae6482._.js")
R.c("server/chunks/5bcb1_next-auth_14556e89._.js")
R.c("server/chunks/5bcb1_openid-client_743813e2._.js")
R.c("server/chunks/5bcb1_jose_dist_node_cjs_21f3c926._.js")
R.c("server/chunks/5bcb1_00c9395d._.js")
R.c("server/chunks/[root-of-the-server]__61b03fed._.js")
R.c("server/chunks/apps_web__next-internal_server_app_api_auth_[___nextauth]_route_actions_2a92b308.js")
R.m("[project]/apps/web/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/apps/web/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
