#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage:
  DRAPIXAI_RELEASE_REGISTRY=registry.example/drapixai \
  DRAPIXAI_EXPECTED_GIT_REF=<40-character-release-commit> \
  bash deploy/scripts/publish-release-images.sh [deploy/env/ai.production.env]

Builds the API, web, and Standard CatVTON runtime from one clean release commit,
blocks publication on HIGH/CRITICAL image findings, pushes the artifacts, and
writes immutable digest references to runtime/release-images/<commit>.env.
Registry credentials must be provided by the operator's Docker credential helper.
EOF
  exit 2
}

[[ $# -le 1 ]] || usage
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ai_env="${1:-$repo_root/deploy/env/ai.production.env}"

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_command docker
require_command git
docker buildx version >/dev/null 2>&1 || {
  echo "Docker Buildx is required to resolve pushed release image digests." >&2
  exit 1
}
[[ -f "$ai_env" ]] || { echo "Missing AI production env file: $ai_env" >&2; exit 1; }

set -a
source "$ai_env"
set +a
[[ "${DRAPIXAI_AI_RUNTIME_IMAGE:-}" =~ ^pytorch/pytorch:[a-zA-Z0-9._-]+@sha256:[a-f0-9]{64}$ ]] || {
  echo "DRAPIXAI_AI_RUNTIME_IMAGE must be the digest-pinned approved PyTorch base before release publication." >&2
  exit 1
}

registry="${DRAPIXAI_RELEASE_REGISTRY:-}"
[[ "$registry" =~ ^[a-z0-9][a-z0-9._:/-]*[a-z0-9]$ ]] || {
  echo "DRAPIXAI_RELEASE_REGISTRY must be a lowercase registry namespace such as ghcr.io/acme/drapixai." >&2
  exit 1
}
expected_ref="${DRAPIXAI_EXPECTED_GIT_REF:-}"
[[ "$expected_ref" =~ ^[a-f0-9]{40}$ ]] || {
  echo "DRAPIXAI_EXPECTED_GIT_REF must be an exact 40-character release commit." >&2
  exit 1
}
expected_commit="$(git -C "$repo_root" rev-parse "${expected_ref}^{commit}" 2>/dev/null || true)"
current_commit="$(git -C "$repo_root" rev-parse HEAD)"
[[ -n "$expected_commit" && "$expected_commit" == "$current_commit" ]] || {
  echo "Checkout does not match DRAPIXAI_EXPECTED_GIT_REF." >&2
  exit 1
}
[[ -z "$(git -C "$repo_root" status --porcelain)" ]] || {
  echo "Release publication requires a clean checkout." >&2
  exit 1
}

api_tag="$registry/api:$current_commit"
web_tag="$registry/web:$current_commit"
ai_tag="$registry/ai:$current_commit"

docker build --platform linux/amd64 \
  --label "org.opencontainers.image.revision=$current_commit" \
  -f "$repo_root/apps/api/Dockerfile" -t "$api_tag" "$repo_root"
docker build --platform linux/amd64 \
  --label "org.opencontainers.image.revision=$current_commit" \
  -f "$repo_root/apps/web/Dockerfile" -t "$web_tag" "$repo_root"
docker build --platform linux/amd64 \
  --label "org.opencontainers.image.revision=$current_commit" \
  --build-arg "DRAPIXAI_AI_BASE_IMAGE=$DRAPIXAI_AI_RUNTIME_IMAGE" \
  -f "$repo_root/drapixai_ai/docker/Dockerfile" -t "$ai_tag" "$repo_root"

bash "$repo_root/deploy/scripts/scan-container-images.sh" "$api_tag" "$web_tag" "$ai_tag"
docker push "$api_tag"
docker push "$web_tag"
docker push "$ai_tag"

resolve_digest() {
  local image="$1"
  local digest
  digest="$(docker buildx imagetools inspect "$image" 2>/dev/null | awk '/^Digest:/ { print $2; exit }')"
  [[ "$digest" =~ ^sha256:[a-f0-9]{64}$ ]] || {
    echo "Could not resolve an immutable digest for $image." >&2
    exit 1
  }
  printf '%s@%s' "${image%:*}" "$digest"
}

api_image="$(resolve_digest "$api_tag")"
web_image="$(resolve_digest "$web_tag")"
ai_image="$(resolve_digest "$ai_tag")"
output_dir="${DRAPIXAI_RELEASE_OUTPUT_DIR:-$repo_root/runtime/release-images}"
mkdir -p "$output_dir"
output_file="$output_dir/$current_commit.env"
cat > "$output_file" <<EOF
# Generated by deploy/scripts/publish-release-images.sh. Do not edit.
DRAPIXAI_RELEASE_COMMIT=$current_commit
DRAPIXAI_API_RELEASE_IMAGE=$api_image
DRAPIXAI_WEB_RELEASE_IMAGE=$web_image
DRAPIXAI_AI_RELEASE_IMAGE=$ai_image
EOF
chmod 0600 "$output_file"

printf 'Published immutable release references: %s\n' "$output_file"
printf 'Use this file only with the matching commit and production env files.\n'
