#!/usr/bin/env bash
set -euo pipefail

export DRAPIXAI_APP_ROOT="${DRAPIXAI_APP_ROOT:-/workspace/drapixai}"

DRAPIXAI_AI_ENV_FILE="${DRAPIXAI_AI_ENV_FILE:-$DRAPIXAI_APP_ROOT/deploy/env/ai.runpod.env}"
if [[ -f "$DRAPIXAI_AI_ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$DRAPIXAI_AI_ENV_FILE"
  set +a
fi

export DRAPIXAI_VENV="${DRAPIXAI_VENV:-$DRAPIXAI_APP_ROOT/.venv}"

if ! python - <<'PY' >/dev/null 2>&1
import sys
raise SystemExit(0 if sys.version_info[:2] == (3, 11) else 1)
PY
then
  if command -v python3.11 >/dev/null 2>&1; then
    DRAPIXAI_PYTHON_SHIM_DIR="${DRAPIXAI_PYTHON_SHIM_DIR:-/tmp/drapixai-python311}"
    mkdir -p "$DRAPIXAI_PYTHON_SHIM_DIR"
    ln -sf "$(command -v python3.11)" "$DRAPIXAI_PYTHON_SHIM_DIR/python"
    export PATH="$DRAPIXAI_PYTHON_SHIM_DIR:$PATH"
  fi
fi

if [[ -x "$DRAPIXAI_VENV/bin/python" ]]; then
  export VIRTUAL_ENV="$DRAPIXAI_VENV"
  export PATH="$DRAPIXAI_VENV/bin:$PATH"
fi
export DRAPIXAI_AI_VALIDATION_PROFILE="${DRAPIXAI_AI_VALIDATION_PROFILE:-ai}"

export DRAPIXAI_TRYON_ENGINE="${DRAPIXAI_TRYON_ENGINE:-catvton}"
export DRAPIXAI_CATVTON_MODEL_DIR="${DRAPIXAI_CATVTON_MODEL_DIR:-$DRAPIXAI_APP_ROOT/models/catvton}"
export DRAPIXAI_MODEL_DIR="${DRAPIXAI_MODEL_DIR:-$DRAPIXAI_CATVTON_MODEL_DIR}"
export DRAPIXAI_FASHN_WEIGHTS_DIR="${DRAPIXAI_FASHN_WEIGHTS_DIR:-$DRAPIXAI_APP_ROOT/models/fashn-vton-1.5}"
export DRAPIXAI_CATVTON_BASE_MODEL="${DRAPIXAI_CATVTON_BASE_MODEL:-$DRAPIXAI_APP_ROOT/models/stable-diffusion-inpainting}"
export DRAPIXAI_CATVTON_VAE_MODEL="${DRAPIXAI_CATVTON_VAE_MODEL:-$DRAPIXAI_APP_ROOT/models/sd-vae-ft-mse}"
export DRAPIXAI_GARMENT_CACHE_DIR="${DRAPIXAI_GARMENT_CACHE_DIR:-$DRAPIXAI_APP_ROOT/runtime/garments}"
export DRAPIXAI_TRANSIENT_SPOOL_DIR="${DRAPIXAI_TRANSIENT_SPOOL_DIR:-/dev/shm/drapixai-tryon-spool}"
export DRAPIXAI_GPU_PRESET="${DRAPIXAI_GPU_PRESET:-runpod-a100}"
export DRAPIXAI_RUNTIME_CACHE_ROOT="${DRAPIXAI_RUNTIME_CACHE_ROOT:-$DRAPIXAI_APP_ROOT/runtime/cache}"
export HF_HOME="${HF_HOME:-$DRAPIXAI_RUNTIME_CACHE_ROOT/huggingface}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-$HF_HOME/hub}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
export TORCH_HOME="${TORCH_HOME:-$DRAPIXAI_RUNTIME_CACHE_ROOT/torch}"
export U2NET_HOME="${U2NET_HOME:-$DRAPIXAI_RUNTIME_CACHE_ROOT/u2net}"
export PYTHONPATH="${DRAPIXAI_APP_ROOT}${PYTHONPATH:+:${PYTHONPATH}}"

mkdir -p \
  "$DRAPIXAI_APP_ROOT/models" \
  "$DRAPIXAI_APP_ROOT/runtime/logs" \
  "$DRAPIXAI_GARMENT_CACHE_DIR" \
  "$DRAPIXAI_TRANSIENT_SPOOL_DIR" \
  "$DRAPIXAI_RUNTIME_CACHE_ROOT" \
  "$HF_HOME" \
  "$HUGGINGFACE_HUB_CACHE" \
  "$TRANSFORMERS_CACHE" \
  "$TORCH_HOME" \
  "$U2NET_HOME"

cd "$DRAPIXAI_APP_ROOT"
