#!/usr/bin/env bash
set -euo pipefail

export DRAPIXAI_APP_ROOT="${DRAPIXAI_APP_ROOT:-/workspace/drapixai}"
export DRAPIXAI_MODEL_DIR="${DRAPIXAI_MODEL_DIR:-$DRAPIXAI_APP_ROOT/models/idm_vton}"
export DRAPIXAI_GARMENT_CACHE_DIR="${DRAPIXAI_GARMENT_CACHE_DIR:-$DRAPIXAI_APP_ROOT/runtime/garments}"
export DRAPIXAI_GPU_PRESET="${DRAPIXAI_GPU_PRESET:-runpod-a100}"
export DRAPIXAI_RUNTIME_CACHE_ROOT="${DRAPIXAI_RUNTIME_CACHE_ROOT:-$DRAPIXAI_APP_ROOT/runtime/cache}"
export HF_HOME="${HF_HOME:-$DRAPIXAI_RUNTIME_CACHE_ROOT/huggingface}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-$HF_HOME/hub}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
export TORCH_HOME="${TORCH_HOME:-$DRAPIXAI_RUNTIME_CACHE_ROOT/torch}"
export U2NET_HOME="${U2NET_HOME:-$DRAPIXAI_RUNTIME_CACHE_ROOT/u2net}"
export PYTHONPATH="${DRAPIXAI_APP_ROOT}${PYTHONPATH:+:${PYTHONPATH}}"

mkdir -p \
  "$DRAPIXAI_APP_ROOT/models" \
  "$DRAPIXAI_APP_ROOT/runtime/logs" \
  "$DRAPIXAI_GARMENT_CACHE_DIR" \
  "$DRAPIXAI_RUNTIME_CACHE_ROOT" \
  "$HF_HOME" \
  "$HUGGINGFACE_HUB_CACHE" \
  "$TRANSFORMERS_CACHE" \
  "$TORCH_HOME" \
  "$U2NET_HOME"

cd "$DRAPIXAI_APP_ROOT"
